"""Web UI presets (M6_DESIGN.md sections 3, 5, 6): traffic presets, defaults, and limits.

Traffic presets are the bundled public trace samples (`data/traces/samples/`, generated by
`scripts/make_samples.py`) plus one synthetic preset. The UI never parses a full public
trace. No Streamlit import here, so the presets are testable on their own.
"""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from llmplan.catalog.hardware import DATA_DIR
from llmplan.catalog.models import DEFAULT_FIXTURE_DIR, FIXTURE_PREFIX
from llmplan.planner import SLO
from llmplan.types import DType
from llmplan.workload import Distribution, Workload, generate, load_workload

SAMPLES_DIR = DATA_DIR / "traces" / "samples"

# Limits (section 6). The upload cap is checked before any parsing.
MAX_UPLOAD_BYTES = 50_000_000
MAX_TIME_LIMIT_S = 30.0
MAX_SIM_REQUESTS = 200_000
MAX_PLANS_PER_HOUR = 30

# Defaults (section 3).
DEFAULT_SLO = SLO(ttft_ms_p95=500.0, tpot_ms_p95=50.0, utilization_target=0.8)
DEFAULT_MAX_MODEL_LEN = 8192
DEFAULT_TIME_LIMIT_S = 10.0
TP_CHOICES = (1, 2, 4, 8)
DTYPE_CHOICES: tuple[DType, ...] = ("bf16", "fp16", "fp8", "int8", "int4")
DEFAULT_DTYPES: tuple[DType, ...] = ("bf16", "fp8")
MAX_NUM_SEQS_CHOICES = (16, 32, 64, 128, 256, 512)
DEFAULT_MAX_NUM_SEQS = (32, 64, 128, 256)
PERF_BACKENDS = ("auto", "roofline", "table")
CLASS_CHOICES = ("2x2", "1", "3x3")  # M7: request-size classes; the first is the default
SOLVERS = ("highs", "cp_sat", "scip", "gurobi")

# Model picker: shipped fixtures (offline) and popular dense Hugging Face ids (fetched only
# when a plan runs). The gpt2 fixture is the unsupported-architecture test case, not offered.
FIXTURE_MODELS = tuple(
    f"{FIXTURE_PREFIX}{path.stem}"
    for path in sorted(DEFAULT_FIXTURE_DIR.glob("*.json"))
    if path.stem != "gpt2"
)
POPULAR_MODELS = (
    "meta-llama/Llama-3.1-8B-Instruct",
    "meta-llama/Llama-3.1-70B-Instruct",
    "Qwen/Qwen2.5-7B-Instruct",
    "Qwen/Qwen3-8B",
    "mistralai/Mistral-7B-Instruct-v0.3",
)
DEFAULT_MODEL = f"{FIXTURE_PREFIX}llama3-8b"

# Token lengths of the synthetic preset and the synthetic form (`workload synth` defaults).
DEFAULT_IN_TOKENS = "lognormal:6.2:0.8"
DEFAULT_OUT_TOKENS = "lognormal:5.5:0.9"


class SamplePreset(BaseModel):
    """A bundled sample: `filename` under `SAMPLES_DIR` in the generic `csv` format, with
    its row count and the public dataset it was cut from."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    key: str = Field(min_length=1)
    label: str = Field(min_length=1)
    filename: str = Field(pattern=r"^[a-z0-9_-]+\.csv$")
    rows: int = Field(gt=0)
    source_url: str = Field(pattern=r"^https://\S+$")


class SyntheticPreset(BaseModel):
    """A seeded synthetic Poisson workload (`llmplan.workload.generate`)."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    key: str = Field(min_length=1)
    label: str = Field(min_length=1)
    rate_rps: float = Field(gt=0)
    duration_s: float = Field(gt=0)
    input_tokens: Distribution
    output_tokens: Distribution
    seed: int = Field(default=0, ge=0)


TracePreset = SamplePreset | SyntheticPreset

SYNTHETIC_PRESET = SyntheticPreset(
    key="synthetic-2rps-1h",
    label="Synthetic: 2 req/s for 1 hour (Poisson, chat-like token lengths)",
    rate_rps=2.0,
    duration_s=3600.0,
    input_tokens=Distribution(kind="lognormal", mean=6.2, sigma=0.8),
    output_tokens=Distribution(kind="lognormal", mean=5.5, sigma=0.9),
)

_AZURE = "https://github.com/Azure/AzurePublicDataset"
# Rows and windows: data/traces/samples/README.md (scripts/make_samples.py output).
SAMPLE_PRESETS: tuple[SamplePreset, ...] = (
    SamplePreset(
        key="azure2024-conv",
        label="Azure 2024 conversation: busiest + median hour (4.6% of rows)",
        filename="azure2024_conv.csv",
        rows=19_999,
        source_url=_AZURE,
    ),
    SamplePreset(
        key="azure2024-code",
        label="Azure 2024 code: busiest + median hour (5.5% of rows)",
        filename="azure2024_code.csv",
        rows=19_999,
        source_url=_AZURE,
    ),
    SamplePreset(
        key="azure2023-conv",
        label="Azure 2023 conversation: whole trace (58 min)",
        filename="azure2023_conv.csv",
        rows=19_366,
        source_url=_AZURE,
    ),
    SamplePreset(
        key="azure2023-code",
        label="Azure 2023 code: whole trace (57 min)",
        filename="azure2023_code.csv",
        rows=8_819,
        source_url=_AZURE,
    ),
    SamplePreset(
        key="burstgpt-1",
        label="BurstGPT: busiest + median hour (60% of rows)",
        filename="burstgpt_1.csv",
        rows=19_999,
        source_url="https://github.com/HPMLL/BurstGPT",
    ),
)

PRESETS: tuple[TracePreset, ...] = (*SAMPLE_PRESETS, SYNTHETIC_PRESET)


def preset(key: str) -> TracePreset:
    """The preset with `key`; raises `KeyError` naming the known keys otherwise."""
    for candidate in PRESETS:
        if candidate.key == key:
            return candidate
    raise KeyError(f"unknown preset {key!r}; known: {', '.join(p.key for p in PRESETS)}")


def load_preset(chosen: TracePreset) -> Workload:
    """The workload of a preset: a bundled sample parsed as generic `csv` (from the package
    data directory, never a user path), or the synthetic workload generated from its seed."""
    if isinstance(chosen, SamplePreset):
        return load_workload(SAMPLES_DIR / chosen.filename, format="csv")
    return generate(
        rate_rps=chosen.rate_rps,
        duration_s=chosen.duration_s,
        input_tokens=chosen.input_tokens,
        output_tokens=chosen.output_tokens,
        seed=chosen.seed,
    )
